# Generated by Django 5.0.3 on 2024-04-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='checked',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deleted',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='value',
        ),
    ]
